# Generated by Django 3.2 on 2021-04-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egonet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='alter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alter',
            name='neighbors',
            field=models.ManyToManyField(blank=True, related_name='_egonet_alter_neighbors_+', through='egonet.Relationship', to='egonet.Alter'),
        ),
        migrations.AlterField(
            model_name='alter',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(1, 'Higher'), (2, 'Similar'), (3, 'Lower'), (4, 'Self employed'), (5, 'Not working')], help_text="Contact's formal rank in the organization he/she works for", null=True, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='ego',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='ego',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
